name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Free disk space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          df -h
      - name: Install linting tools only
        run: |
          pip install --upgrade pip
          pip install flake8 mypy black
      - name: Lint with flake8 (critical errors only)
        run: |
          flake8 ml/ scripts/ --count --select=E9,F63,F7,F82 --show-source --statistics
      - name: Lint with flake8 (warnings - non-blocking)
        run: |
          flake8 ml/ scripts/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        continue-on-error: true
      - name: Check formatting with black (non-blocking)
        run: |
          black --check ml/ scripts/
        continue-on-error: true

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Free disk space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          df -h
      - name: Install dependencies (CPU-only PyTorch for CI)
        run: |
          pip install --upgrade pip
          # Install CPU-only PyTorch to save space (tests don't need GPU)
          pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
          # Install other dependencies
          pip install --no-deps -r requirements.txt || pip install -r requirements.txt
          # Reinstall with dependencies if needed
          pip install numpy pandas pillow scipy scikit-learn matplotlib tqdm pytest
      - name: Run tests
        run: |
          echo "Running pytest..."
          pytest tests/ -v --tb=short --maxfail=5

